// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdf8LW4nsQd3oKr6u09JYF2y4fhp0Hgzs',
    appId: '1:988978687982:web:bba56317bfdec36077a8ff',
    messagingSenderId: '988978687982',
    projectId: 'fitness-tracker-7a228',
    authDomain: 'fitness-tracker-7a228.firebaseapp.com',
    storageBucket: 'fitness-tracker-7a228.firebasestorage.app',
    measurementId: 'G-MF07LHY72F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3IhoQMrROlXzP4RxPGu4J5MGkgWnvYic',
    appId: '1:988978687982:ios:c3ff2ffab84ce11877a8ff',
    messagingSenderId: '988978687982',
    projectId: 'fitness-tracker-7a228',
    storageBucket: 'fitness-tracker-7a228.firebasestorage.app',
    iosClientId: '988978687982-0ura29u3sceaeepfha465u4hdb5b1na5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3IhoQMrROlXzP4RxPGu4J5MGkgWnvYic',
    appId: '1:988978687982:ios:c3ff2ffab84ce11877a8ff',
    messagingSenderId: '988978687982',
    projectId: 'fitness-tracker-7a228',
    storageBucket: 'fitness-tracker-7a228.firebasestorage.app',
    iosClientId: '988978687982-0ura29u3sceaeepfha465u4hdb5b1na5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdf8LW4nsQd3oKr6u09JYF2y4fhp0Hgzs',
    appId: '1:988978687982:web:ce6bb1207a5972fc77a8ff',
    messagingSenderId: '988978687982',
    projectId: 'fitness-tracker-7a228',
    authDomain: 'fitness-tracker-7a228.firebaseapp.com',
    storageBucket: 'fitness-tracker-7a228.firebasestorage.app',
    measurementId: 'G-K9CFDP6B24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2gkZgXEtH40i40HSW0nAvdTUBNTLgKwA',
    appId: '1:988978687982:android:1711bd3d6146ebf677a8ff',
    messagingSenderId: '988978687982',
    projectId: 'fitness-tracker-7a228',
    storageBucket: 'fitness-tracker-7a228.firebasestorage.app',
  );

}